### ISSUE TITLE
[Feature Request] Custom AI Instruction

### ISSUE THREAD

**Issue by evilalmus** [glibsonoran/Plush-for-ComfyUI#104]
It would be really nice to be able to easaly modify the AI Instruction on the fly, Ir to be able to override the built in instruction on a case-by-case basis. Not a big deal because I can edit the config.json, but it gets recreated every time Comfy is reloaded.

**Comment by glibsonoran** [comment]
Hi, you can write your own custom instructions using the *Advanced Prompt Enhancer* (APE) node in the Plush Suite.  Simply apply your instruction to the instruction input.  The *Style Prompt* node is for people that want to use a per-constructed instruction.  

Just FYI the Plush files, including the .json files, do get refreshed when you run a *git pull*: i.e.: You update your custom nodes.

**Comment by evilalmus** [comment]
yup, not sure why I didn't try APE before I made this request. It does exactly what I wanted. Thank you.
