### ISSUE TITLE
[Feature Request] NLPcloud API support.

### ISSUE THREAD

**Issue by evilalmus** [glibsonoran/Plush-for-ComfyUI#106]
The API reference is here: https://docs.nlpcloud.com/#generation. It seems to be close but not quite like the OpenAI API.

**Comment by glibsonoran** [comment]
I've taken a look at this site and I really can't support this company's API.  It's completely proprietary, not all like the OpenAI standard.  It's reasonable for me to have enough time to maintain this node suite if I have a standard to code to, even though  I support several implementations, but trying to support wholly proprietary API's is something I don't have the bandwidth for.
Sorry...

**Comment by evilalmus** [comment]
Thank you for taking a look.
