### ISSUE TITLE
Do i need to download the Groq models?

### ISSUE THREAD

**Issue by karthikg-09** [glibsonoran/Plush-for-ComfyUI#107]
![image](https://github.com/user-attachments/assets/fbabfb17-3335-4782-9ba9-a9259e50bbcb)

Not getting models to select in the drop-down

how to fix this?

**Comment by glibsonoran** [comment]
Did you get a key from Groq and put it in the environment variable?

**Comment by karthikg-09** [comment]
yes
``` 
echo "export LLM_KEY=gsk_xxxxx" >> ~/.zshrc
source ~/.zshrc
echo $LLM_KEY

**Comment by karthikg-09** [comment]
it's working now. some issue with my machine.
anyways thank you for the quick response and the amazing node

**Comment by glibsonoran** [comment]
OK, glad it's working, enjoy!
