### ISSUE TITLE
Feature Request: Add Sambanova and Huggingface Inference API variables

### ISSUE THREAD

**Issue by EnragedAntelope** [glibsonoran/Plush-for-ComfyUI#115]
Hi,
I love Plush nodes and use them daily!
Is it possible to include Sambanova? It uses standard OpenAI chat completion (https://api.sambanova.ai/v1/chat/completions) , it just needs the API key set and a model selected. It is free and offers Meta Llama 405B! https://cloud.sambanova.ai/apis

Separately, Huggingface offers free API inference, not sure if that is something that could also be included? https://huggingface.co/docs/api-inference/index

Thank you!

**Comment by glibsonoran** [comment]
I don't have an account with Sambanova so it won't let me see anything using that link.  However if it is truly OpenAI compliant you should be able to use: "Local app (URL)" or "OpenAI compatible http POST (URL)" on the AI_Services menu if you first put your API key into an `LLM_KEY` environment variable.  Then just add the URL for the service in the `LLM_URL` field and it should work.

**Comment by glibsonoran** [comment]
Note that using "OpenAI compatible http POST (URL)" will require a URL that has a [your http address]/v1/chat/completions path as its format.  "Local app (URL)"  will automatically format the path for you, so you can just leave the longer path in place.

**Comment by EnragedAntelope** [comment]
Thank you, I just tried your suggestions, but Sambanova (main page https://cloud.sambanova.ai/ ) works like Groq where you have to select a model. It currently offers 3 variants of Llama 3.1 (8, 70, 405).  So I get a "server could not process the request" even after setting the LLM key and trying the different options.

**Comment by glibsonoran** [comment]
Hmm, while this won't address your issue completely we might be able to fake the program out a little and test to see if it will work when supplied with a model name.  

Do you have Ollama?  If so load up Ollama and load one of the models that are also used at Sambanova (Hopefully the model names will be the same.)  Then start ComfyUI.  You should see a list of the models available in Ollama in the Ollama models pulldown.  PIck a model that also exists at Sambanova and choose one of the AI Service type that makes the connection and use the Sambanova URL.  That should connect and allow you to use the same model that Ollama was indicating.

To fix this permanently I'll probably have to add back the blank model field again so you can enter random model names.

**Comment by EnragedAntelope** [comment]
I tried this but unfortunately Ollama calls it "llama3.1:latest" which doesn't match Sambanova's listing (equivalent model there shows as "Meta-Llama-3.1-8B-Instruct". So still a "Server was unable to process this request" message. 

![image](https://github.com/user-attachments/assets/29ac15b5-8fd6-4c0f-9cf3-7836bc21c86a)

![image](https://github.com/user-attachments/assets/26acdb68-8b70-403f-bee6-d48142ab89de)

**Comment by glibsonoran** [comment]
I see, well... I think there's one more thing we can try if you're game: 

I believe Ollama has a command that allows you to make a pointer to a model and give it any name you like.  

`ollama cp llama3.1:latest Meta-Lama-3.1-8B-Instruct`

Then if you start up ollama it should have a pointer that will then show up in your list of models in Plush.  Well, I hope anyway... lol

Try it if you want, I'll try and find some time to add an optional model name field.

**Comment by glibsonoran** [comment]
FYI, using the ollama model names:  You may have select*Ollama* in the AI_services menu.

**Comment by EnragedAntelope** [comment]
Good thinking for troubleshooting steps. Unfortunately it didn't work, I suspect because the Ollama model field still appends ":latest" ? I copied the model to the exact name required but you can see that it shows up differently:
![image](https://github.com/user-attachments/assets/39352b16-251d-47b6-b725-c922c84d68e3)

You have that neat fetch model code, I wonder if it could allow intake from any API somehow (not sure if that's different per service even if OpenAI compatible chat completions - you definitely know more than me on this :) ).

**Comment by glibsonoran** [comment]
OK, there's a new version up 1.21.15 that should solve your problem.  It has a new field *optional_model* and there's a new text file that supports it.  The instructions for the new field and text file is in the help output of Advanced Prompt Enhancer and in the comment header of the text file.

Let me know if you have any issues.

**Comment by EnragedAntelope** [comment]
You did it!!! Awesome. I am now using my first ever 405B model... to create prompts for silly images. I gotta work on that. Still, amazing!

I wish I had more than one star to give. Thank you.

For awareness these additional options are not yet reflected in the AI Chooser node. 

In case others want to setup for Sambanova I had to enter this as URL:
https://api.sambanova.ai/v1/chat/completions

And added these lines to optional models:
SambaNova::Meta-Llama-3.1-8B-Instruct
SambaNova::Meta-Llama-3.1-70B-Instruct
SambaNova::Meta-Llama-3.1-405B-Instruct

I have not yet tried Huggingface, I don't yet totally understand the structure involved but hope to try that over next few days.

![image](https://github.com/user-attachments/assets/a50dd419-df33-40ac-94e5-c09ccd7c3948)

**Comment by glibsonoran** [comment]
Great, and thanks for the star. 
Do me a favor and run a quick test:  Try doing a git pull on your installation, and make sure it doesn't overwrite your optional_models.txt file input. I haven't used .gitattributes before, I set it always choose the user's file when there's a merge, I just want to make sure this works.

**Comment by EnragedAntelope** [comment]
Tested, not sure if the fatal error is the expected output. I usually only manage my comfy custom nodes via the manager inside comfy. But I did confirm after I tested that my optional models changes were still in place.


```
D:\ComfyUI\custom_nodes>git pull https://github.com/glibsonoran/Plush-for-ComfyUI
remote: Enumerating objects: 1463, done.
remote: Counting objects: 100% (474/474), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 1463 (delta 293), reused 397 (delta 259), pack-reused 989 (from 1)
Receiving objects: 100% (1463/1463), 37.50 MiB | 54.70 MiB/s, done.
Resolving deltas: 100% (918/918), done.
From https://github.com/glibsonoran/Plush-for-ComfyUI
 * branch            HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

**Comment by EnragedAntelope** [comment]
FYI I did an update all from Comfy Manager and restarted comfy, and have lost my optional models. Just wanted to let you know of that behavior.

**Comment by glibsonoran** [comment]
Oh... too bad.  I wonder why?  Maybe the manager does a git clone?  

Welp back to the drawing board on this.  I mean this will work for you, although inconveniently, until I create the code to generate an un-tracked file.  In the meantime you might want to make a backup copy after you enter your models like: "optional_models.bak";  then you can go in after a Manager update and make a copy of that file and rename it to ".txt".  Or if you're ambitious you can run a little .bat file script to automatically rename it:

`@echo off
copy /Y optional_models.bak optional_models.txt
if %errorlevel% equ 0 (
    echo File copied successfully.
) else (
    echo An error occurred while copying the file.
)
pause`

Meantime, I'll see what I can do to get around it.

**Comment by glibsonoran** [comment]
OK, new fix out.  This will be the untracked file: `opt_models.txt`, your old *optional_models.txt* file will probably be deleted when you update.
The new `opt_models.txt` file is created when Plush first runs (that's how I keep it from being tracked by github) so it won't be there right after you update, you'll have to run ComfyUI first. Then the file will appear.

Let me know if you have any issues, and if your data can survive a Manager update.

**Comment by EnragedAntelope** [comment]
Confirmed all is good! Thank you. I filled in the new opt_models file, saved, restarted comfy and saw my models listed. Then updated comfy and plush nodes via Manager, restarted again, and confirmed everything is still there. Well done!

I haven't been able to test the HF thing yet but I want to close this so it doesn't hang out there too long. 

I appreciate all of your work!
