### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by bo4rsworld** [glibsonoran/Plush-for-ComfyUI#118]
2024-09-28 22:56:41,817 - root - INFO - Prompt executed in 0.03 seconds
2024-09-28 23:00:49,703 - root - INFO - got prompt
2024-09-28 23:00:49,745 - root - ERROR - !!! Exception during processing !!! empty separator
2024-09-28 23:00:49,746 - root - ERROR - Traceback (most recent call last):
  File "G:\AI_stories\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI_stories\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI_stories\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\AI_stories\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI_stories\ComfyUI_windows_portable\ComfyUI\custom_nodes\Plush-for-ComfyUI\style_prompt.py", line 763, in gogo
    example_list = self.j_mngr.build_context(Examples, delimiter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI_stories\ComfyUI_windows_portable\ComfyUI\custom_nodes\Plush-for-ComfyUI\mng_json.py", line 1292, in build_context
    segments = [seg.strip() for seg in input_data.split(delimiter)]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: empty separator

2024-09-28 23:00:49,749 - root - INFO - Prompt executed in 0.03 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by glibsonoran** [comment]
Hmm, let me look at this I'll get back to you.

**Comment by glibsonoran** [comment]
OK, what I think is happening is that the Advanced Prompt Enhancer UI might be screwed up.  Since my previous update (before the most current one) changed the UI for Advanced Prompt Enhancer by adding the *Optional_model* field.  Sometimes after a UI change like that you have to reload the node otherwise the values in each field are offset from what they should be. 

The error you're getting means you passed in an empty string as the delimiter "", but you can't do that because it's not an option in the UI... Unless the UI values are offset like I described above.

So try creating a new Advanced Prompt Enhancer node and replacing it in your workflow and see if that fixes the problem.  In the mean time I'll make a little change in the code so it's impossible to pass an empty string.

**Comment by glibsonoran** [comment]
OK, try reloading the node into your workflow as I said above.
I have now set the default value of the delimiter to None, so this should stop that error from happening.  However, while you might not get an error, if your Advanced Prompt Enhancer UI values are offset you're still going to not get the result you expect unless you reload it.

**Comment by bo4rsworld** [comment]
I replaced the node and the error disappeared. All nodes were linked in the same way, but llm still doesn't work as it should. 
Guess I'll have to look again for myself to see what the problem is.
I'm will still figuring that out too. Thank you very much for your time and help, have a nice weekend!

**Comment by glibsonoran** [comment]
It looks like you're trying to use examples.  I put an example workflow in the example_workflows folders called: *How to use examples*  maybe that will help.

**Comment by bo4rsworld** [comment]
I look at it and yes, that was a finished workflow. I just rebuilt and expanded it a bit and was a bit overwhelmed, but a test run is currently running and everything is working again, thank you

**Comment by glibsonoran** [comment]
Yay! :)

**Comment by glibsonoran** [comment]
Closed
