### ISSUE TITLE
Tagger Node Feature request

### ISSUE THREAD

**Issue by rafstahelin** [glibsonoran/Plush-for-ComfyUI#128]
I know this might not be a general need for everyone but I am looking for a way to insert RANDOMLY a tag into the generated caption. The tagger already has the great beginning, middle, end, but if running a batch process from many image captioning generations, would be great to add seed randomisation for where the tagger places the token. I dont know if this is easy to do, but would really enhance image captioning for training

**Comment by glibsonoran** [comment]
So you have a tag you want to place in a caption, but you want to randomly, for each workflow run, place it either at the top middle or end of the caption... is that correct?

**Comment by rafstahelin** [comment]
yes, i want to randomise per caption, so if i run 10 images for captioning, some will be in the beginning, some in the middle, some at the end. The idea is mix the activation token so that it doesnt overfit in the training. But essentially, the randomising is for batch captioning yes

**Comment by glibsonoran** [comment]
Ok, so I don't really want to add a "randomize" feature to Tagger.  I just think the use case for this is too niche. 

However a couple of general utility nodes might help you and that might be worthwhile:
*   A *Randomizer*:  Has one text input and 5 text outputs and a field where you enter a number between 1 and 5.  The node randomly selects  the output between output-1 and output-n, where n is the number you entered in the field.  So in the case of Tagger, you could hook a multiline text output node that contains your tag up to the "Randomizer" input node; enter 3 as the number of random outputs, then hook output-1 to Beginning_Tags, output-2 to Middle_Tags and output-3 to End_Tags, output's 4 & 5 would always output an empty string when the number is set to 3.  This would apply your tag randomly to one of the three positions each run, with the potential to do this for up to 5 positions if you were using it for some other reason.  
*   A *Mixer* node: Has 5 text inputs and 5 text outputs.  The node randomizes the correlation between inputs and outputs based on the number of inputs you hook up.  So if you hook up three inputs, outputs 1,2&3 will provide the input data in some randomized order (e.g. input1 -> output2, input2->output3, input3->output1).  The other outputs will provide empty strings.  The outputs that will have valid data will always be output-1 through output-n where n is the number of active inputs.  So this would work in the case where you had more than one tag (or whatever) you want to randomize.

**Comment by rafstahelin** [comment]
awesome, thanks for the suggestion!

**Comment by glibsonoran** [comment]
The nodes are done.  So do demonstrate, here's a node setup that will:
*  Randomly select one of three tags
* Randomly apply the selected tag to one of three positions in the Main text: Beginning, Middle, End.
![Randoms](https://github.com/user-attachments/assets/585574d5-ab5f-4571-8ff0-2e0504abfc0c)

**Comment by glibsonoran** [comment]
This is up on the repo now v.1.21.18.1

**Comment by rafstahelin** [comment]
> The nodes are done. So do demonstrate, here's a node setup that will:
> 
> * Randomly select one of three tags
> * Randomly apply the selected tag to one of three positions in the Main text: Beginning, Middle, End.
>   ![Randoms](https://private-user-images.githubusercontent.com/31249593/377257382-585574d5-ab5f-4571-8ff0-2e0504abfc0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTUxMjAsIm5iZiI6MTcyOTE1NDgyMCwicGF0aCI6Ii8zMTI0OTU5My8zNzcyNTczODItNTg1NTc0ZDUtYWI1Zi00NTcxLThmZjAtMmUwNTA0YWJmYzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA4NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMTQyZDEzN2ViMmUwZDkwNGNlNDhlNjRlMThiZTZlMmZiZTZhOTA3OTI0NTY5NjZmMzdlNDZhZmVjMTExOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7EOCJmHOBPmITs4OPHSHPTHCJ--Fl1Ete49JLeaM-g)

testing

**Comment by rafstahelin** [comment]
beautiful works super nice

**Comment by glibsonoran** [comment]
Closed
