### ISSUE TITLE
groq working on comfyui but not on Plush

### ISSUE THREAD

**Issue by rafstahelin** [glibsonoran/Plush-for-ComfyUI#129]
I ended up using 

`set OPENAI_API_KEY=` in the comfyui start bat file and both gpt and claude work fine now. 

I am using groq llama 3.2 11b vision with api configured as above, on a different comfyui node, and it works

On Plush Prompt Enhancer I have it set to  llama 3.2 11b vision as well but it doesnt work 

 using [https://api.groq.com/v1/chat/completions](https://api.groq.com/v1/chat/completions%5B1)

![image](https://github.com/user-attachments/assets/e7f7eb36-8da6-4735-a454-e774947f02ee)

Just wondering if there's something i am missing

**Comment by rafstahelin** [comment]
![image](https://github.com/user-attachments/assets/16031d4d-977b-4bd6-a32e-13f4afd71b67)

**Comment by glibsonoran** [comment]
Groq - and any of the AI service menu items that don't end in *(URL)* - don't need a value in LLM_URL.  They all have built in URLs.  If you've updated your Plush-for-ComfyUI suite in the last two days, you should have *Add Parameters* as your top input above *Image*.  If you have done this recent update: Create a new Advanced Prompt Enhancer node -> hook it up to your workflow -> delete the old Advanced Prompt Enhancer node -> make sure your settings are as you want them then try your workflow. 
When the UI gets updated on these nodes, they tend to fail on workflows that have been built with old versions of the node.
Let me know if this fixes your problem.

**Comment by glibsonoran** [comment]
By the way as long as you have an Environment Variable: `GROQ_API_KEY` set to your Groq key, that's all it should take to make Groq work with the Advanced Prompt Enhancer.  You don't need anything in the .bat file.
