### ISSUE TITLE
Please have a example of api keys.

### ISSUE THREAD

**Issue by KINGLIFER** [glibsonoran/Plush-for-ComfyUI#133]
I was attempting to to use setx GROQ_API_KEY in windows and I have tried ( ) and without brackets with no success. The Api I got from the site is brand new and I get the error message: 

➤ Begin Log for: Advanced Prompt Enhancer, Node #144:
✦ INFO: Additional parameters input: []
✦ INFO: No model selected. If you're using a local desktop application, most will just use the loaded model.
✦ INFO: Converting Torch Tensor image to b64 Image file
✦ INFO: Setting client to OpenAI Groq LLM object
✦ ERROR: Server STATUS error 401: Invalid API Key.
✦ ERROR: Server was unable to process this request. Error: Error message missing

Can you show an example (can be random) of what the cmd prompt I would be using if I was using GROQ. Yes I saw what you said, I just need to see an example please.

**Comment by glibsonoran** [comment]
First make sure you've opened your command window as Administrator (right click and choose *open as Administrator*.  Then, an example of the command is:

setx GROG_API_KEY gsk_1234

Where *gsk_1234* is just what I'm using to represent the value of your actual key. Then open a **new command window** and type:

 echo %GROQ_API_KEY%
 
 That should return the key value, and confirms the key was set.  Then restart ComfyUI

**Comment by KINGLIFER** [comment]
Hate installing nodes... but gotta if you want to try new things... 
So I wanted to be sure... (and thank you) but this isn't working. Very straight forward. I added the api and did it how you stated and I assumed you needed Administrator privileges.  but I assumed there was more to it since I was getting an error.

✦ INFO: Converting Torch Tensor image to b64 Image file
✦ INFO: Setting client to OpenAI Groq LLM object
✦ ERROR: Server STATUS error 401: Invalid API Key.
✦ ERROR: Server was unable to process this request. Error: Error message missing

I am using portable version of comfyUi

**Comment by glibsonoran** [comment]
The message: ✦ ERROR: Server STATUS error 401: Invalid API Key.
Is a return value that Advanced Prompt Enhancer is getting from Groq reporting your key invalid.

*   Are you sure you entered your key value correctly, like you didn't accidentally cut a few characters off when you copy pasted it?
    *    check the last and first three characters of your key and compare it to your saved values, to make sure it's all there
*   Could there be some reason for Groq not to honor your key?

**Comment by glibsonoran** [comment]
If you can you might want to run your key in another app that uses the api to see if it works there.

Also if you just made you key, it may take a while for them to activate it.

You can examine your key in it env variable by going to Windows -> System -> Advanced System Settings -> Advanced (Tab) -> Environment Variables -> Locate your key in the upper list and press *Edit* to examine the value.

**Comment by EnragedAntelope** [comment]
Don’t forget reboot after setting the key if you have just set the env variable. Unless you’ve successfully tested with the echo? Either way also have to restart comfy. I comfirm Plush works incredibly well with Groq.

**Comment by KINGLIFER** [comment]
> Don’t forget reboot after setting the key if you have just set the env variable. Unless you’ve successfully tested with the echo? Either way also have to restart comfy. I confirm Plush works incredibly well with Groq.

Ok (creator) Please just adjust the directions just to advise admin permissions and you must reset the system. This was done on a server so I never restarted the entire instance to test. Thanks.

**Comment by glibsonoran** [comment]
closed
