### ISSUE TITLE
Server was unable to process the request

### ISSUE THREAD

**Issue by Autantpourmoi** [glibsonoran/Plush-for-ComfyUI#140]
hi, first i have a knowledge about env variable, etc,etc closed to a red fish one ... i'm trying to use plush with Groq > I made an account on Groq , free one , i generated an API Key , i think i exported it right as echo the api key return the right key numbers , i did pip install groq .
but when i choose groq as ai service i have this response : Server was unable to process the request
i also tried that 
`import os

from groq import Groq

client = Groq(
    api_key=os.environ.get("GROQ_API_KEY"),
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Explain the importance of fast language models",
        }
    ],
    model="llama3-8b-8192",
)

print(chat_completion.choices[0].message.content)`

Which return 

`bash: from: command not found...
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `)'
bash: syntax error near unexpected token `('
bash: role:: command not found...
bash: content:: command not found...
bash: ],: command not found...
bash: syntax error near unexpected token `)'
bash: syntax error near unexpected token `chat_completion.choices[0].message.content'`

Which doesn't sound very good even for my poor knowledge in all that magic code 
Any help will be greatly appreciated 
Advanced prompt enhancer is working locally with ollama 
thanks

**Comment by glibsonoran** [comment]
Well, you can try rebooting.  Also can you hook up a text display node to the 'troubleshooting' output from Advanced Prompt Enhancer?  It will give me a little more information about what's going wrong.

**Comment by glibsonoran** [comment]
Re: your code:
It appear that you're trying to run Python code in a Bash shell.

**Comment by Autantpourmoi** [comment]
does it mean that 'im trying to wash my clothes without water and soap ? sorry but i don't know what it means .

**Comment by glibsonoran** [comment]
Did you hook up the 'troubleshooting' output?  If so paste the output in a message here. 

Regarding your code you were trying to use one programming language in another programming language's interpreter. They don't mix, so it couldn't understand your code. It's like speaking Korean to someone who only speaks Italian.

**Comment by Autantpourmoi** [comment]
➤ Begin Log for: Advanced Prompt Enhancer, Node #205:
✦ INFO: Additional parameters input: []
✦ INFO: No model selected. If you're using a local desktop application, most will just use the loaded model.
✦ INFO: Converting Torch Tensor image to b64 Image file
✦ INFO: Setting client to OpenAI Groq LLM object
✦ ERROR: Server STATUS error 401: Invalid API Key.
✦ ERROR: Server was unable to process this request. Error: Error message missing

hello, this is what i got, so i delete the previous groq api key , renewit , set up a new EnvVariable as described for linux . zshrc , still have the same message and now ollama isn't working anymore

**Comment by glibsonoran** [comment]
Are you using Windows or Linux?  The information I get is just that your API key is invalid.  

You could try this code in your Bash shell (which is what you were using in the first example of code you sent me).  Replace YOUR_API_KEY with your actual key value:
```
curl -H "Authorization: Bearer YOUR_API_KEY" https://api.groq.com/v1/status
```

**Comment by Autantpourmoi** [comment]
i'm using linux , and i set up the new env variable with .zshrc , so i don't know if it's mean that i'm still in bash shell? sorry for my poor understanding of these thing

**Comment by glibsonoran** [comment]
When you type `echo $GROQ_API_KEY` into your terminal does it return your Groq API key value?

**Comment by Autantpourmoi** [comment]
yes

**Comment by Autantpourmoi** [comment]
but at first install as it doesn't seems to work i tried the other solution you advise for env variable  replacing .zshrc with .bash_profile. can my pb come from there . Since i erase my previous apy key, redid everything with .zshrc and everything seems ok as echo $GROQ_API_KEY return my api key numbers

**Comment by glibsonoran** [comment]
Just to be sure, you are selecting 'Groq' in the AI-services menu on the node, right?

**Comment by Autantpourmoi** [comment]
yes

**Comment by Autantpourmoi** [comment]
![image](https://github.com/user-attachments/assets/a4ecba39-1387-4fb9-938c-d91f9bf4ce97)

**Comment by glibsonoran** [comment]
Try running this code is your bash shell:

```
curl -X POST "https://api.groq.com/openai/v1/chat/completions" \
     -H "Authorization: Bearer $GROQ_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"messages": [{"role": "user", "content": "Explain the importance of fast language models"}], "model": "mixtral-8x7b-32768"}'
```

**Comment by Autantpourmoi** [comment]
curl -X POST "https://api.groq.com/openai/v1/chat/completions" \
     -H "Authorization: Bearer $GROQ_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"messages": [{"role": "user", "content": "Explain the importance of fast language models"}], "model": "mixtral-8x7b-32768"}'
{"error":{"message":"Invalid API Key","type":"invalid_request_error","code":"invalid_api_key"}}

**Comment by Autantpourmoi** [comment]
![Screenshot from 2024-10-26 17-41-14](https://github.com/user-attachments/assets/a8912f80-1999-465d-82fb-a872548eed26)

**Comment by glibsonoran** [comment]
It's saying your key is invalid.  So we're getting the same response as Plush/ComfyUI is getting.  The key you have in your env variable is invalid.  I don't really have a way to determine why that's the case.  The common reasons are:

*   You entered your key incorrectly.  Check the first 3 and last 3 characters to make sure the key is complete and didn't get cut off.
* Groq has invalidated your key
* Groq hasn't activated your key yet.

**Comment by Autantpourmoi** [comment]
ok i'll try with a new API KEy
don't know what else to do

**Comment by glibsonoran** [comment]
The other thing would be to try Groq support and see if they can tell you why.  But with that Bash code I just gave you, you have a quick way to check to see if the key is valid.

**Comment by Autantpourmoi** [comment]
i tried them already , no response until monday , i tried their discord but no one could help me so far

**Comment by glibsonoran** [comment]
I don't know why the key is invalid.  When you create your next key, paste a copy into a text doc so you have something you can reference when you check the key value... if you're not already doing this.

**Comment by Autantpourmoi** [comment]
i'll but when you create the api key it's almost impossible to copy an extra space or symbol as it's almost automatic . i renew it already , didn't have time to try it . is it better to restart comfyui or the computer ?

**Comment by glibsonoran** [comment]
Since you're having this trouble, I'd restart the whole computer.

**Comment by Autantpourmoi** [comment]
i did check all env variable .zshrc .bashrc .~/.profile ~/.bash_profile ~/.zprofile, delete all groq api key . actually there was one in bash.profile , did source for each env, check echo until i got nothing associated to groq, restart the computer, create a new account on groq, generate a new api key , followed your instruction and still it returns an invalid key , so i don't know what else to do

**Comment by Autantpourmoi** [comment]
but something change 
curl -X POST "https://api.groq.com/openai/v1/chat/completions" \
     -H "Authorization: Bearer $GROQ_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"messages": [{"role": "user", "content": "Explain the importance of fast language models"}], "model": "mixtral-8x7b-32768"}'
{"id":"chatcmpl-cebd7307-b2ab-4308-ad05-e898dc5c8dac","object":"chat.completion","created":1729962476,"model":"mixtral-8x7b-32768","choices":[{"index":0,"message":{"role":"assistant","content":"Fast language models are important for a variety of reasons. Here are a few:\n\n1. **Real-time applications:** Many natural language processing (NLP) applications require real-time responses. For example, a chatbot needs to understand and respond to user queries quickly, or a speech-to-text transcription service needs to provide real-time subtitles for a live broadcast. Fast language models can help meet these real-time requirements.\n\n2. **Cost-effectiveness:** Training and deploying large language models can be computationally expensive. Fast models can perform similar tasks with less computational resources, making them more cost-effective.\n\n3. **Energy efficiency:** Large language models can have a significant carbon footprint due to the energy required to train and run them. Faster models can perform the same tasks while using less energy, which is better for the environment.\n\n4. **User experience:** Slow models can lead to a poor user experience. For instance, if a search engine takes too long to provide results, users may become frustrated and look elsewhere. Fast language models can help ensure a smooth and responsive user experience.\n\n5. **Accessibility:** Not every device or user has access to high-end computational resources. Fast language models can make advanced NLP capabilities available on low-resource devices, increasing accessibility.\n\nRemember, while speed is important, it's also crucial to maintain accuracy and quality. A fast model that makes many errors won't be useful in the long run. Therefore, the goal is to strike a balance between speed and performance."},"logprobs":null,"finish_reason":"stop"}],"usage":{"queue_time":0.010997968,"prompt_tokens":16,"prompt_time":0.002361232,"completion_tokens":335,"completion_time":0.540554568,"total_tokens":351,"total_time":0.5429158},"system_fingerprint":"fp_c5f20b5bb1","x_groq":{"id":"req_01jb4ws1cnfnh9g8jzwehtmch0"}}

**Comment by glibsonoran** [comment]
Sounds like you had a competing env var with an invalid key value.  So are you getting models in the Groq_models field in Advanced Prompt Enhancer?

**Comment by Autantpourmoi** [comment]
no groq- models still not populated

**Comment by glibsonoran** [comment]
There's one more thing we can try, it's going to require you to make some minor data inputs.  It will tell us if the problem is just with the GROQ_API_KEY env variable or something broader.  

If you want to try it let me know and I"ll give you the directions.

**Comment by Autantpourmoi** [comment]
really appreciate your help , and yes i'm ready to try thing to make it work

**Comment by glibsonoran** [comment]
Ok, for your Groq key let's try this:

*   First create a new Groq API key using the `LLM_KEY` environment variable.  Test it using echo $LLM_KEY to make sure it returns the right value.
* Then go into the Plush-for-ComfyUI directory it's at:  ComfyUI/custom_nodes/Plush-for-ComfyUI  Once there locate the: `opt_models.txt` file and open it in a text editor.  You'll see directions about how to add model names in the comment header (those lines that begin with a "#').  Type in a couple Groq model names like:  
    *   Grog::llama-3.1-70b-versatile
    *   Groq::Gemma2-9b-it
    * Make sure you *don't* preface your lines with a '#' as this renders them not readable.
*    Save the text file and, just to be safe, reboot and then start ComfyUI
* In the Advanced Prompt Enhancer *AI_service* field choose *Local App (URL)*
* In the *Optional_model* field choose one of the Groq models you entered.
* In the *LLM_URL* field enter the url for Groq: `https://api.groq.com/openai/v1`
* Run your workflow and let me know if it works.

**Comment by Autantpourmoi** [comment]
just starting now , before starting i did check if i had a GROQ_API_KEY with echo $GROQ_API_KEY and it didn't return anything but i did check nano ~/.zshrc and there's was a line with my api key but it doesn't seems it was visible by cli >>>Just to let u know and if that ring a bell to you as it doesn't to me lol

**Comment by Autantpourmoi** [comment]
Names still doesn't show, and i check back opt_models.text where i copied/paste the 2 models name u gave me as example and they're here ...
and after reboot echo $LLM_KEY doesn't return anything and if i look for it with nano ~/.zshrc
i see my llm_key registered here

**Comment by glibsonoran** [comment]
You don't see model names in the *Optional_model* field in Advanced Prompt Enhancer?

**Comment by Autantpourmoi** [comment]
ok i meesed up a bit but now , i have the grog model showing in optional_model , i had a pb with the LLM_KEY because on your explanation to set var env you wrote "echo "export OAI_KEY=(yourkey)" >> ~/.zshrc" but i didn't know u shouldn't keep the (). I found out that's why echo llM_key wasn't returning anything .
it still doesn't work but with another message : 
➤ Begin Log for: Advanced Prompt Enhancer, Node #6:
✦ INFO: Additional parameters input: []
✦ INFO: Converting Torch Tensor image to b64 Image file
✦ INFO: Open source LLM URL saved to file.
✦ INFO: Server returned response code: 404
✦ INFO: Using Complex data structure
✦ ERROR: Server was unable to process the request.  Status: 404: {"error":{"message":"Unknown request URL: POST /openai/v1. Please check the URL for typos, or see the docs at https://console.groq.com/docs/","type":"invalid_request_error","code":"unknown_url"}}

**Comment by glibsonoran** [comment]
*   Disconnect your *image* input.  Don't send an image with the prompt
*   The url is: https://api.groq.com/openai/v1

**Comment by Autantpourmoi** [comment]
explanation from groq : When setting up the environment variable, you should not include the word "bearer" in the variable value. Instead, you should set the variable to only the API key, and then use the word "bearer" when authenticating with the API.
So, in your case, you should set the environment variable GROQ_API_KEY to just your API key, without the word "bearer". Then, when using the API, you should include the word "bearer" and a space before your API key in the Authorization header value.
echo "export GROQ_API_KEY=MyKey" >> ~/.zshrc

Then, when authenticating with the API:

Authorization: Bearer MyKey

**Comment by glibsonoran** [comment]
Ahh... I see the problem.  Groq has an unusual url with the *openai* in it.  My program is validating the url and taking the openai out.  
So let's try this:

*  Instead of *Local app {URL}*  let's set *AI_service* to *OpenAI compatible http POST (URL)*  
* Then let's go down to the *LLM_URL* field and enter this URL: `https://api.groq.com/openai/v1/chat/completions`
* Then run your workflow, hopefully this should work.

**Comment by Autantpourmoi** [comment]
i tried it it isn't working 
is it normal that today starting my computer when i echo th LLM_KEY i don't have any return while i have a line export LLM-KEY= MYAPIKEY in nano ~/.zshrc ?
 i need to source ~/.zshrc to see it  ?
![image](https://github.com/user-attachments/assets/c2cf7dab-9939-490e-a9dd-bbaccf94de54)

**Comment by glibsonoran** [comment]
I'm afraid I'm out of ideas. You are having some kind of issue with you environment variables that I can't diagnose. I'm not that familiar with Linux, and I don't think there's any more help I can offer you.

**Comment by Autantpourmoi** [comment]
ok i understand , you tried your best , have a good day

**Comment by glibsonoran** [comment]
Closed
