### ISSUE TITLE
Problem with the grog api url

### ISSUE THREAD

**Issue by Sh4c** [glibsonoran/Plush-for-ComfyUI#141]
Hey, i'm using groq and i set my groq_api_key env var (echo %groq_api_key% works), but i only get errors (401 before and 404 now).
In the Advanced Prompt Enhancer node, i selected groq. I tried with or without url (i think it's for local llm) but i can't make it work.

"HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 404 Not Found""

I'm a bit lost and can't find a solution :c

**Comment by glibsonoran** [comment]
Are you getting a list of Groq models in the drop down?  If so then Groq is connecting and validating your API key.  
If you're selecting 'Groq' in the AI_service menu then you don't need a URL, only the AI_services that end in "(URL)" need a URL in the 'LLM_URL' field.

404 could be a response you'd get from a temporary outage... I just tried Groq on my end and everything works fine.

**Comment by Sh4c** [comment]
Thanks for your reactivity !
I just found out ten minutes ago, claude models was selected.
Everything works perfectly fine thanks ! :D
