### ISSUE TITLE
not an issue far from it ....

### ISSUE THREAD

**Issue by Autantpourmoi** [glibsonoran/Plush-for-ComfyUI#142]
Hi, just to let you know that i had to reinstall comfyui as the wheel was spinning for ever , which was also a good way of deleting some custom nodes i wasn't using anymore > Just to let you know that i didn't change the way i did set env variable but with the new install everything works , chatgpt /groq/ Ollama .
I supposed it was a conflict with a custom nodes or it dependencies , and wanted to thank you again for your help and patience

**Comment by glibsonoran** [comment]
You're very welcome.  I'm glad you were able to get everything working, and I hope you enjoy using the suite. :)

**Comment by Autantpourmoi** [comment]
is it possible to unload the model after text generation ? or decide to keep it load or not ? for local llm

**Comment by glibsonoran** [comment]
I know ollama allows this, here's a post from @EnragedAntelope describing how he does it:

Addendum for Ollama users:
If you want to unload a model from VRAM as soon as it finished processing, set a system environment variable: OLLAMA_KEEP_ALIVE=0.

Restart your PC after setting that, so the system variable takes effect before Ollama starts.
```
Additionally, here are settings that work with Ollama/Plush:

docs at https://github.com/ollama/ollama/blob/main/docs/openai.md

http://127.0.0.1:11434/v1

response_format:: {"type": "json_object"}
frequency_penalty:: 0.2
presence_penalty:: 0
temperature:: 1.0
top_p:: 0.9
```

**Comment by glibsonoran** [comment]
Closed

**Comment by glibsonoran** [comment]
@EnragedAngtelope @Autantpourmoi  
APE version 1.21.21 now supports setting the unload behavior of Ollama models directly from the node.

**Comment by EnragedAntelope** [comment]
I can't tell you how much I appreciate you being on top of stuff like this and making constant improvements.

AND we just got a new Llama 3.3 70B to play with from Groq, already working in Plush it seems!
