### ISSUE TITLE
Using the OpenRouter.ai API (OpenAI compatible)

### ISSUE THREAD

**Issue by mbac** [glibsonoran/Plush-for-ComfyUI#144]
Hi!

I set up my openrouter.ai key as environment var LLM_KEY, and entered their URL (https://openrouter.ai/api/v1/chat/completions) in the LLM_URL field. However, I don't understand where I should enter the model info (`cognitivecomputations/dolphin-mixtral-8x22b`) for this type of connection. Can you please help?

**Comment by glibsonoran** [comment]
Yes,  
*   You need to open the file:  `.../ComfyUI/custom_nodes/Plush-for-ComfyUI/opt_models.txt` . 

*   There'll be a comment header in the text file explaining how to enter model names.  You'll need to start ComfyUI after you've entered the names.  

*   Then look in the `Optional_model` field in Advanced Prompt Enhancer to see your list of models.

**Comment by glibsonoran** [comment]
OK, I'm going to assume this info provided what you needed to use openrouter.  I'll close this issue.  If you're still having problems let me know.

**Comment by mbac** [comment]
Sorry for the late reply. Yes it works fine with this info! Thanks.
