### ISSUE TITLE
APE: how to loop prompt refinement/edit without keep adding nodes

### ISSUE THREAD

**Issue by rafstahelin** [glibsonoran/Plush-for-ComfyUI#149]
Is there a way to loop an output prompt from LLM without continuing on a chain but merely remaining cyclical until result satisfactory? Kind of like a typical chat?
Or does the flow require adding myriad nodes in a series? 
Maybe I'm missing something

**Comment by rafstahelin** [comment]
Maybe like image bridge node, which you can select when you want to loop around to the same refinement of node with option to edit another refinement instruction to the llm

**Comment by glibsonoran** [comment]
I haven't really looked at loops in ConfyUI, but it's an interesting question. Here's a [video I found describing loops in ComfyUI](https://youtu.be/ndnCbeOphiY?si=__k8-PoR1KtjOUuQ). 

I'll see what else I can find. It would make for a good agentic floww to loop a 'prompt writer ' node and a 'prompt evaluator ' node until the evaluator was satisfied with the prompt. Let me know if you find anything.

**Comment by rafstahelin** [comment]
I remember seeing this custom node 

ControlFlowUtils
Which has 

• Loop nodes for repeating actions multiple times
	•	Cycle functionality for processing data through successive prompts
	•	Wait nodes to introduce delays between operations

Will look in a bit deeper. But yea that's essentially what I was looking for.

**Comment by glibsonoran** [comment]
My *Agents_example* in the  Example_Workflows folder uses this logic, but without looping. It's just a single pass.
