### ISSUE TITLE
HTTP Request: POST http://127.0.0.1:11434/chat/completions "HTTP/1.1 404 Not Found"

### ISSUE THREAD

**Issue by 2259819800** [glibsonoran/Plush-for-ComfyUI#152]
output:Server was unable to process the request

**Comment by 2259819800** [comment]
➤ Begin Log for: Advanced Prompt Enhancer, Node #316:
✦ INFO: Additional parameters input: []
✦ INFO: Converting Torch Tensor image to b64 Image file
✦ INFO: Local LLM Server is running with status code: 200
✦ INFO: Setting client to OpenAI Open Source LLM object
✦ INFO: Maximum tries set to: 1
✦ ERROR: Non-retryable error occurred: 404 page not found
✦ ERROR: Request failed: 404 page not found

**Comment by EnragedAntelope** [comment]
Assuming ollama is running (?) , try changing chat/completions in the URL to v1

**Comment by 2259819800** [comment]
Thank you very much. The method you provided is excellent and effective.

**Comment by glibsonoran** [comment]
Yay!
