### ISSUE TITLE
Gemini 2 flash api when it comes out

### ISSUE THREAD

**Issue by rafstahelin** [glibsonoran/Plush-for-ComfyUI#155]
Would be nice

**Comment by glibsonoran** [comment]
It's running now on OpenRouter: "google/gemini-2.0-flash-exp:free", however these gemini experimental models on OpenRouter tend to be highly rate limited and return errors because they're so impacted with traffic.

If you want to use OpenRouter, [see here](https://github.com/glibsonoran/Plush-for-ComfyUI?tab=readme-ov-file#how-to-connect-to-openrouter)

As for Google's API, when I looked at it last it was very non-standard, i.e.: not OpenAI compatible, which makes sense I guess.  I'll look at it again and see how difficult it might be to integrate.

**Comment by glibsonoran** [comment]
close

**Comment by rafstahelin** [comment]
> It's running now on OpenRouter: "google/gemini-2.0-flash-exp:free", however these gemini experimental models on OpenRouter tend to be highly rate limited and return errors because they're so impacted with traffic.
> 
> 
> 
> If you want to use OpenRouter, [see here](https://github.com/glibsonoran/Plush-for-ComfyUI?tab=readme-ov-file#how-to-connect-to-openrouter)
> 
> 
> 
> As for Google's API, when I looked at it last it was very non-standard, i.e.: not OpenAI compatible, which makes sense I guess.  I'll look at it again and see how difficult it might be to integrate.

Ok, I think I will go the open router way then, and yes until they become more available--it's not pressing. Thanks ☺️

**Comment by rafstahelin** [comment]
> It's running now on OpenRouter: "google/gemini-2.0-flash-exp:free", however these gemini experimental models on OpenRouter tend to be highly rate limited and return errors because they're so impacted with traffic.
> 
> If you want to use OpenRouter, [see here](https://github.com/glibsonoran/Plush-for-ComfyUI?tab=readme-ov-file#how-to-connect-to-openrouter)
> 
> As for Google's API, when I looked at it last it was very non-standard, i.e.: not OpenAI compatible, which makes sense I guess. I'll look at it again and see how difficult it might be to integrate.

Hello again. I am interested in running Gemini GEMINI_API_KEY via the Google API provider. Would this possible now? 

I also would like to try XAI_API_KEY

I've been trying with the Custom API KEY node without much success. 

I have them in env variables. Anthropic works fine, as it is integrated into APE.

**Comment by glibsonoran** [comment]
I'm working on adding Gemini now, along with multiple images (although many llm's seem to be barely able to handle two in my testing).  

You can make any env variable name you want and use it with the custom envelope variable node, but will only work with APE AI Services the have a '(URL)' ending

**Comment by rafstahelin** [comment]
i've found that starting with Sonnet 3.7 latest and Gemini Flash 2.0 Pro both manage to understand a 1st and 2nd image instruction to integrate aspects from each respectively, quite well, which was not possible before. Here's an example. I asked to use identity of first image and integrate the look and feel of the 2nd image:
<img width="898" alt="Image" src="https://github.com/user-attachments/assets/f139d953-ab3a-4896-ad79-2ad8c528fa4c" />

The issue with gemini and the other services, is none of them have the url ending. 

I've been using the custom api node with LLM_KEY="token" and GEMINI_API_KEY="token" in runpod env var (which works fine for anthropic)

I've tried 
GEMINI_API_KEY in runpod env variables (template) which works fine for other llm nodes like IF_LLM


https://generativelanguage.googleapis.com/v1beta/openai https://generativelanguage.googleapis.com/v1beta/
https://generativelanguage.googleapis.com/v1beta

I select OpenAI API Connection (URL) and tried the above url's

No luck, still not getting a connection

<img width="1197" alt="Image" src="https://github.com/user-attachments/assets/ca55535f-00b2-49b9-b064-b756a5368f89" />

**Comment by rafstahelin** [comment]
apologies for posting silly images

**Comment by glibsonoran** [comment]
What kind of error do you get?

**Comment by rafstahelin** [comment]
"HTTP/1.1 404 Not Found"

**Comment by glibsonoran** [comment]
OK I got it to work with: https://generativelanguage.googleapis.com/v1beta/openai/ (mind the forward slash at the end). Don't use GEMINI_API_KEY as your env. var name, I've got that reserved for the Gemini specific rollout.  As you can see I used: MY_GEMINI_VAR but there's nothing special about that you can use any name that's not already in use for other services.

I noticed a bug also, when using `OpenAI API Connection (URL)` it seemed to work fine if I ran this first thing right after boot.  But it didn't pick up the custom key if I ran it after having run another inference first.  So try that.

Here's a screen shot of the result of my run:

![Image](https://github.com/user-attachments/assets/94d15571-5895-43ff-a47d-d2ec1aa946e6)

**Comment by rafstahelin** [comment]
Sup! Going to see Bong Joon Ho's Mickey 17 for some inspo and i ll test it when i am back, Excited

**Comment by glibsonoran** [comment]
Here's the multi image input.  This is using `style_prompt` but it works the same way with APE.  The `Batch Images` node is a standard ComfyUI node, it's not a custom node, and of course this is using the new built-in Gemini AI_Service.  This will all be in the next release:

![Image](https://github.com/user-attachments/assets/dc3e0aaf-7435-4014-91a6-da20fb848378)

**Comment by rafstahelin** [comment]
Awesome gemini-2.0-flash is working for me
I also tired grok-2-vision-1212 with https://api.x.ai/v1 which works, but not grok-3 or grok-3-latest
When are you releasing the batch image feature and Ai Chooser. 
That will be dope, the three best models. Could you include grok too? 
This is massive, thank you so much

**Comment by glibsonoran** [comment]
I just merged it, it's available now.  I haven't updated the ReadMe yet, but you know pretty much what's up.

**Comment by rafstahelin** [comment]
Super! Thank you indeed

**Comment by glibsonoran** [comment]
I'm not going to be including Grok as a built-in service.  

When you find that you can access older models and not newer ones at a particular service, it might be because your account is free or not paid at a high enough level to qualify for the newer models.

**Comment by rafstahelin** [comment]
Yea makes sense.

Will APE get the dropdown service for Gemini at some point as well? I guess it requires a lot more coding 

I just ask because I use json format instructions for complex captioning and promoting 

Just wondering

**Comment by glibsonoran** [comment]
APE has it now.

**Comment by EnragedAntelope** [comment]
> I'm not going to be including Grok as a built-in service.
> 
> When you find that you can access older models and not newer ones at a particular service, it might be because your account is free or not paid at a high enough level to qualify for the newer models.

I am so glad you won’t be including Grok. No one should use that… utter trash! 
Sorry 😀 but thank you for adding in Gemini and all of your continued upkeep.

**Comment by rafstahelin** [comment]
Yea, tested it. Awful

**Comment by rafstahelin** [comment]
> APE has it now.

Thank you!

**Comment by rafstahelin** [comment]
Not sure what this error is due to
Boolean value of Tensor with more than one value is ambiguous

<img width="925" alt="Image" src="https://github.com/user-attachments/assets/0196ba92-e7a8-4774-a2f4-4c427676c090" />

<img width="593" alt="Image" src="https://github.com/user-attachments/assets/c29b8ab1-6a21-4413-b7e0-ef4f6307d0bc" />

**Comment by glibsonoran** [comment]
Update your suite and it should be fixed now.

**Comment by rafstahelin** [comment]
I have a question. Is there a Plush node that can load text from a txt file, say for saved prompts? I see Load Saved Files, but it seems this is reserved for parameters and metadata. I have quite a few prompts that I want to be able to load to prompt the llm instead of in a text to string node. Just thought I'd ask

**Comment by glibsonoran** [comment]
Yes the `Save Text` and `Load Text` nodes from *Custom Scripts* will allow you to save and load your text files.  I think Custom Scripts is built-in to Comfy now.  Anyway they're the nodes from pysssss with the snake graphic on them.

**Comment by rafstahelin** [comment]
super. i've implemented everything. You've made a solid update. Thank you so much!

**Comment by glibsonoran** [comment]
Glad you've found it useful.
