### ISSUE TITLE
How do we specify that the "Examples_or_context" is context not an example?

### ISSUE THREAD

**Issue by GamingDaveUk** [glibsonoran/Plush-for-ComfyUI#157]
Creating a work flow where i am adding section detail bit by bit and feeding in the previous generated context from the context output of the last node to the Examples_or_context node of the next one, but it keeps using it as an example and thus doubling up sections. How do I tell it to use it as context and not an example?

**Comment by glibsonoran** [comment]
The model is going to determine how to treat your context/example input based on the structure of the prompt(s) you give it ie. what you tell it to do.  So if you want the model to add new content in the same context as the content before, building a completed text output one step at time, you should tell it that explicitly in a System Prompt.  "Consider the context of the previous responses and add more content in a manner consistent with those previous responses.  Don't repeat content." or something like that.  

Make sure you attach the System Prompt to each of the nodes in the progression, as the System Prompt is not carried over in the Context Output.

**Comment by glibsonoran** [comment]
There's a [thread here](https://github.com/glibsonoran/Plush-for-ComfyUI/discussions/132) where I use APE to create a storytelling like conversation that might be something like you're describing.

**Comment by GamingDaveUk** [comment]
> The model is going to determine how to treat your context/example input based on the structure of the prompt(s) you give it ie. what you tell it to do. So if you want the model to add new content in the same context as the content before, building a completed text output one step at time, you should tell it that explicitly in a System Prompt [Instruction input]. "Consider the context of the previous responses and add more content in a manner consistent with those previous responses. Don't repeat content." or something like that.
> 
> Make sure you attach the System Prompt to each of the nodes in the progression, as the System Prompt is not carried over in the Context Output.
> 
> Or you can make a unique System Prompt for each node if that suites your purpose better, just make sure you tell the model clearly how you want it to treat the context information and what type of output you want.

Hmm I am going to need to rethinkl my approach when more awake lol. 
So to be clear Example_or_context does not have a way to discern which it is, it just gets given to the AI along with the prompt?

**Comment by glibsonoran** [comment]
No, there's no switch or flag to indicate which is which.  It's simply a feed of all the user inputs followed by model responses that have gone before.  Just like Silly Tavern keeps track of your story dialogue and feeds it back to the model so it knows the context and what's been said.

The *How_to_use_Examples.png* file in the 'Plush-for-ComfyUI/Example_Workflows' directory shows you some uses of this.

**Comment by glibsonoran** [comment]
closed
