### ISSUE TITLE
HTTP/1.1 429 Too Many Requests

### ISSUE THREAD

**Issue by KINGLIFER** [glibsonoran/Plush-for-ComfyUI#158]
I keep getting Retrying request to /chat/completions in 1.689504 seconds
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"

Using chat gtp. Any advice?

**Comment by glibsonoran** [comment]
Hmmm ChatGPT has been having outages over the past couple of days. Can you use it through its web interface?

**Comment by KINGLIFER** [comment]
Yes. Could my subscription be the issue? I have a personal plus.

**Comment by glibsonoran** [comment]
Well the error message is saying you're not providing an API key, not that you don't have rights to the model or something. I assume that it has been working for you before and now just started throwing this error?  

Given all the issues OpenAI has been having in the the past couple of days, I just wonder if their key validation process is temporarily broken. Anyway I' I'll try testing it was on my side, but I can't do it right now.

**Comment by glibsonoran** [comment]
OK, I was able to try it quickly this morning and everything worked fine for me.  Are you still having the issue?

**Comment by glibsonoran** [comment]
I'm sorry, I misread your post.  You're having a problem with too many requests, not your api key.  

My retry code should wait an increasing amount of time between retries.  Can you tell me what you're seeing in your *troubleshooting* output?

**Comment by KINGLIFER** [comment]
of course. Happy Holidays.

**Comment by glibsonoran** [comment]
Lol.  It was 6am here and I'd just woken up when I read your message.  I clicked the link in your post thinking it was a link to the error message and got this:

{
message | "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys."
type | "invalid_request_error"
param | null
code | null
}

So anyway...  Oy

**Comment by KINGLIFER** [comment]
I have added the api as instructed and did the echo test so may I ask why would that error occur?

**Comment by glibsonoran** [comment]
Hmmm, "too many requests" error: 429, is something that would occur if the app were pushing a lot of completion requests one after another.  I'm not seeing that when I use APE, what OS are you using?

**Comment by KINGLIFER** [comment]
Windows. Using stability matrix if that means anything.

**Comment by glibsonoran** [comment]
Try setting "Tries" to 1 and see if that changes anything.

**Comment by EnragedAntelope** [comment]
hi, the api key for Groq goes in a system environment variable BEFORE you launch comfy. 
no spaces
In windows I use the command in my bat file before comfy launches:

set GROQ_API_KEY=xxxxxxxxxxxx

**Comment by glibsonoran** [comment]
```
How to Setup Your Environment Variables

An environment variable is a variable that is set on your operating system, rather than within your application. It consists of a name and value. For a paid ChatGPT key you can set the name of the variable to: OAI_KEY or OPENAI_API_KEY. If you're using an Open-source product that requires or can use a key (most do not), or a remote serivce that's not preconfigured, use the environment variable: LLM_KEY. Refer to the table above for other services. The example below only refers to 'OAI_KEY' but you can substitute the environment variable name that applies to you per the [table](https://github.com/glibsonoran/Plush-for-ComfyUI/blob/main/README.md#your-openai-api-or-open-source-key-optional-not-required-for-exif-wrangler-switch-nodes-or-advanced-prompt-enhancer-when-used-with-open-source-llms) above.

Note that after you set your Enviroment Variable, you will have to reboot your machine in order for it to take effect.
Windows Set-up

Option 1: Set your ‘OAI_KEY’ Environment Variable via the cmd prompt with admin privileges.

Run the following in the cmd prompt, replacing with your API key:

setx OAI_KEY (your key)

You can validate that this variable has been set by opening a new cmd prompt window and typing in

echo %OAI_KEY%

Option 2: Set your ‘OAI_KEY’ Environment Variable through the Control Panel

    Open System properties by right clicking the windows startup button and selecting "System". Then select Advanced system settings

    Select Environment Variables...

    Select New… from the User variables section(top). Add your name/key value pair ('OAI_KEY/'jk-####'), replacing (yourkey) with your API key.

Variable name: OAI_KEY Variable value: (yourkey)

In either case if you're having trouble and getting an invalid key response, per the instructions above, please try rebooting your machine.
```

**Comment by glibsonoran** [comment]
You might try Option 2 in the post above if you're having trouble.  You'll have more control over how you enter the information.

**Comment by KINGLIFER** [comment]
Yeah did that and saw my api sitting there. its ok thought I could this to work it is straight forward directions but I guess my setup is not working. 

Thanks anyway.
