### ISSUE TITLE
Plush Won't Import

### ISSUE THREAD

**Issue by stealurfaces** [glibsonoran/Plush-for-ComfyUI#16]
Hi! Having some trouble. I have my API key dialed in, I have the openai v1.5 package installed, but Plush still won't import: 

"Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\Plush-for-ComfyUI\__init__.py", line 46, in <module>
    from . import style_prompt
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\Plush-for-ComfyUI\style_prompt.py", line 3, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (C:\AI\ComfyUI\python_embeded\lib\site-packages\openai\__init__.py)

Cannot import C:\AI\ComfyUI\ComfyUI\custom_nodes\Plush-for-ComfyUI module for custom nodes: cannot import name 'OpenAI' from 'openai' (C:\AI\ComfyUI\python_embeded\lib\site-packages\openai\__init__.py)"

Thoughts? Many thanks!

**Comment by glibsonoran** [comment]
The error seems to be: "ImportError: cannot import name 'OpenAI' from 'openai'"  The older versions of openai package did not have this (OpenAI) module.  Are you using the Windows Portable version of ComfyUI?  (If so there would be a "ComfyUI_Windows_Portable" directory that's the parent of the ComfyUI directory)  If you have a working version of Python installed and you are using the Windows Portable ComfyUI, you have to make sure you apply any package changes to the correct Python installation as you have two of them (python embedded is what Windows Portable Comfy is using).

So first I'd try deleting the Push-for-ComfyUI directory from ComfyUI/custom_nodes (you can save out the "config.json' if you don't want to reenter your key.  Just remember to copy it back into the directory when yo reinstall.) Then reinstall using the Manager in Comfy per my instructions in the ReadMe.  Manager should run my requirements.txt and upgrade your openai.

If this doesn't fix it, you can try this: 

= In the command window navigate to this directory in your ComfyUI installation: 
\ComfyUI_windows_portable\python_embeded\Scripts.

= In the "Scripts directory type this on the command line: "pip install openai --upgrade"

= Then, while still in the scripts directory type: "pip show openai" and look through the result to find the version listing and confirm that it's 1.3.5 or later.

**Comment by stealurfaces** [comment]
I tried both of your suggestions with versions 1.3.5 and 1.5 (confirmed like you said), and I'm getting the same error. I just signed up for the API today so maybe the key isn't working yet? Will try again tomorrow.

**Comment by glibsonoran** [comment]
OK, is the error the same, or did it change?  Because you wouldn't get that error, or the inability to load the node, as a result of an invalid key.  With an invalid key you'd load the node and then get an "invalid key" error when you tried to run your workflow.

The error you showed in your initial message is almost certainly from a missing or misversioned openai package.

**Comment by Torcelllo** [comment]
This node is missing :)

![Capture](https://github.com/glibsonoran/Plush-for-ComfyUI/assets/114806454/afaf64a4-80dd-4f7e-8675-61c103b97248)

**Comment by glibsonoran** [comment]
Torcello:  Run ComfyUI, then switch over to the terminal output (cmd window).  Press Ctrl-F and search for "plush" in the text.  You'll probably find a couple of hits but one will of them will show you the error that occurred on load.  Let me know what that says.

**Comment by Torcelllo** [comment]
I am getting a lot of IMPORT FAILED Errors, but Plush is no error
![plush](https://github.com/glibsonoran/Plush-for-ComfyUI/assets/114806454/218bef83-ce2e-4045-9890-222c2be42f17)

**Comment by glibsonoran** [comment]
That's strange. :\  Are there any other entries in the command window that you can find with "plush"?

**Comment by Torcelllo** [comment]
None I'm afraid!

**Comment by Torcelllo** [comment]
Why am I getting all those Failed to Import Errors at all?

**Comment by glibsonoran** [comment]
OK you failed importing efficiency-nodes-comfyui, so now do a  search on "efficiency" in the terminal window.  You should see a message indicating what happened and a path to the .py file for efficiency nodes.

**Comment by Torcelllo** [comment]
Just the two lines here ...

![efficiency](https://github.com/glibsonoran/Plush-for-ComfyUI/assets/114806454/f709f9a9-d959-43dd-b3d1-da00a31747ae)

**Comment by Torcelllo** [comment]
Are these errors because I once used ComfyUI Portable, and the Libraries still think that they are in the Python_embeded folder?

**Comment by glibsonoran** [comment]
Hmm I don't know enough about Comfy to really answer that.  Here's a couple of things you can try.
=First if you haven't updated Comfy in a while, startup comfyui, go into the manager and select Update ComfyUI
= Then in the manager select Update All
= Quit then restart Comfy and see if any of your load failures were fixed
********
= Otherwise I'd make a good screenshot of your terminal so you remember all the nodes you have.  Then I'd delete Comfy completely and reinstall it.
=Then start it up and load each node you want through the manager.
Ugh... I know!

That's all I can think of though.

**Comment by glibsonoran** [comment]
Stealurfaces:  I added some code to my __init__.py file that prints out in the terminal view the actual version of openai that Plush is seeing.  If you reinstall plush, or if you run a git pull on it, you'll get the new __init__ file and you can search for "Plush" in the terminal (cmd) output after starting comfy and see what version printed there.

**Comment by glibsonoran** [comment]
Torcello:  Oh and if you have to reinstall.  Make sure you go in and save out all your workflow .json's and your template .json's (if you made any).  So you make sure not to lose them.

**Comment by stealurfaces** [comment]
So first I confirmed that my PC, running Python 3.10.6, has the openai v_1.5 package installed. I then opened Comfy and looked for Plush in the terminal . . .

"Plush - Current Openai Version:  0.28.1
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\Plush-for-ComfyUI\__init__.py", line 51, in <module>
    from . import style_prompt
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\Plush-for-ComfyUI\style_prompt.py", line 3, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (C:\AI\ComfyUI\python_embeded\lib\site-packages\openai\__init__.py)"

v_0.28.1 - Whoa! Sorry to say I have no idea how to fix this. Learning as I go here . . . Thoughts?

**Comment by glibsonoran** [comment]
Your path: "C:\AI\ComfyUI\ComfyUI\nodes.py"  does not indicate a Windows Portable installation.  I'd expect a directory structure like: C:\AI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI/.  Have you installed ComfyUI more than once?  Do you launch Comfy from a shortcut?  If so right click it and select "properties" and look at the path and file that it's pointing to.  Maybe you're not running the windows portable version.
***********
If you're running something other than Windows Portable, Comfy is using one of your python installations from the Windows py launcher.  To find out where these are, open your command window and type: "py -0p"  That's a zero not the letter O.
You should see a path to all the python installations py launcher knows about.  
*  Open your command window
*  Go to the directory(s) listed by py -0p one by one
* Go into the scripts subdirectory:   cd scripts
* When you get there type pip show openai
* if you find one that has version 0.28.1 that's the culprit
* type pip install openai --upgrade
* type pip show openai to confirm the upgrade
* Try launching Comfy again

**Comment by stealurfaces** [comment]
Sorry, maybe I misunderstand what you mean by Windows "portable installation". In any event, I do launch from a shortcut that points to the \ComfyUI\run_nvidia_gpu.bat. I followed your below-the-line instructions, found just one directory, and confirmed it has version 1.5:

C:\Users\###\AppData\Local\Programs\Python\Python310\Scripts>pip show openai
WARNING: Ignoring invalid distribution -rapt (c:\users\###\appdata\local\programs\python\python310\lib\site-packages)
Name: openai
Version: 1.5.0
Summary: The official Python library for the openai API
Home-page:
Author:
Author-email: OpenAI <support@openai.com>
License:
Location: c:\users\###\appdata\local\programs\python\python310\lib\site-packages
Requires: anyio, distro, httpx, pydantic, sniffio, tqdm, typing-extensions
Required-by:

**Comment by glibsonoran** [comment]
What's the full path to run_nvidia_gpu.bat in your shortcut?

**Comment by stealurfaces** [comment]
C:\AI\ComfyUI\run_nvidia_gpu.bat

**Comment by glibsonoran** [comment]
Hmmm, can you open the file with a text editor (like notepad) and copy the contents so I can see it.  Just close it with no save

**Comment by glibsonoran** [comment]
*the run_nvidia_gpu.bat file

**Comment by stealurfaces** [comment]
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
pause

**Comment by glibsonoran** [comment]
OK your python installation should be at: C:\AI\ComfyUI\python_embedded.  
In the command line entering:   "pip show openai"  in the C:\AI\ComfyUI\python_embedded\Scripts directory, should show you the python installation that has the 0.28.1 version.  Make sure the "location" attribute in the pip show output points to: 
C:\AI\ComfyUI\python_embedded
**************************
If that doesn't work, I'm kind of at a loss.
You're using a python installation that has the old openai library in it somewhere... :\
Anyway, maybe this will work. Let me know

**Comment by stealurfaces** [comment]
Didn't work. Oh well, I'll keep at it. I found this article, which might interest you -- https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/migration?tabs=python%2Cdalle-fix 

("Upgrading from version 0.28.1 to version 1.x is a breaking change, you'll need to test and update your code." )

Thanks for your help!

**Comment by glibsonoran** [comment]
That's too bad.  Thanks for the link, I"ll check it out.  The only other thing you might be able to do is in the Windows File Explorer run a global search on each of your drives C:, D: etc for python.exe and see if you python somewhere other than the two places we've already checked.  Anyway sorry it didn't work :(
