### ISSUE TITLE
Question for the chat node

### ISSUE THREAD

**Issue by alanhuang67** [glibsonoran/Plush-for-ComfyUI#44]
Hello, this look great and I'm going to try it later!

I saw the example, not sure if you have a node for chat function? maybe I can use fix prompt and ask GPT to generation image prompt for some purpose?

Thanks!

**Comment by glibsonoran** [comment]
Chat function?  The style prompt node uses ChatGPT to generate a prompt from your prompt, an image or both. Is that what you're talking about?

**Comment by alanhuang67** [comment]
I will consider another scenario, but it may not be suitable for use in comfyui. For example, I make a storybook, and then use prompt to output the story content and corresponding pictures at the same time?...

**Comment by glibsonoran** [comment]
Yes, you'd have to make a custom instruction for charGPT, something along the lines of:  
"You're a writer and illustrator who writes highly creative stories and draws illustrations depicting scenes from the story.  I'll give you a prompt describing the story setting and characters and you will writes a 500 word short story and provide three illustrations of the most interesting scenes from the story".
