### ISSUE TITLE
The Tagger node appends an unwanted dot to the processed prompt

### ISSUE THREAD

**Issue by alessandroperilli** [glibsonoran/Plush-for-ComfyUI#76]
After 1h of debugging, I realised that the Tagger node adds a dot at the end of the string, no matter how you set it up.

That extra dot has 2 effects:

1. It prevents the workflow that uses Tagger from reproducing the same results produced by the default workflow when no tag is applied.
2. At least with my prompts, it makes the generated images subtly but noticeably more blurred.

**Comment by glibsonoran** [comment]
Are you talking about adding a period to the end of the raw generated text or to the end of the tag placed at the end of the raw generated text.  

 Also, what happened with the </s>?

**Comment by alessandroperilli** [comment]
Sorry I wasn't clear:

If the tagger is there but configured to do nothing, it will add the period:

<img width="740" alt="Screenshot 2024-05-20 at 22 52 42" src="https://github.com/glibsonoran/Plush-for-ComfyUI/assets/9775949/ecee5f46-8d2c-484c-8b0e-1e15a87d883a">

If I bypass it, this is what I get (and should get):

<img width="799" alt="Screenshot 2024-05-20 at 22 44 57" src="https://github.com/glibsonoran/Plush-for-ComfyUI/assets/9775949/84f2c930-8964-4935-afa8-7c170b89f373">

<hr />

The mystery of `</s>` remains unsolved for now. I was about to troubleshoot that when I finally solved this other mystery that afflicted me for days.  I will follow up on that one on the Dev repo.

Thank you!

**Comment by glibsonoran** [comment]
Try tagger now and see if it behaves as you expect.

**Comment by glibsonoran** [comment]
*Tagger from the Dev Repo.

**Comment by alessandroperilli** [comment]
It's perfect now, thank you.
