### ISSUE TITLE
[Feature Request] Support using Ollama for local LLMs.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [glibsonoran/Plush-for-ComfyUI#94]
Ollama requires that one of the installed LLMs are specified in the request, but there's no way to do that with these nodes.
For example, an Ollama specific node queries the server to see what LLMs are available and they appear in the dropdown menu to select.
![image](https://github.com/user-attachments/assets/0decf37a-1d38-4d1e-8e41-388638f63701)

**Comment by glibsonoran** [comment]
Yah it doesn't support Ollama right now.  As you illustrated there's already a pretty comprehensive dedicated Ollama node out there.  I might add it in the future, but honestly, given the other node, this is the first request I've gotten and my repo's been up a year.  

It's kind of hard for me to find the time to work on the suite right now... so, no promises but I may take a look at it later.

**Comment by glibsonoran** [comment]
Closed

**Comment by glibsonoran** [comment]
I added a field *optional_local_model*  to *Advanced Prompt Enhancer* that will allow you to type in the name of the model you want to specify for Ollama.  It's not as convenient as having a list to choose from, but it's a quick fix.  I'll look at providing a list later.

**Comment by glibsonoran** [comment]
Close
